apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - uid: prometheus
    orgId: 1
    name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 2.47.0
  